name: CI

on:
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+.x"
    tags:
      - "v*"

  pull_request:
    branches:
      - "**"

env:
  AWS_REGION: "eu-central-1"
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build-linux-x86_64-pre-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
        shell: bash

      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-workspace-crates: "true"

      - name: Fmt check
        run: cargo fmt --check

      - name: Build
        run: cargo build --locked --release

      - name: Test
        run: cargo test --locked --release --all-features --all-targets

      - name: Lint project crates
        run: cargo clippy --locked --release --all-features --all-targets --no-deps
